.Dd March 27, 2026
.Dt PAX 1
.Os Kayako
.Sh NAME
.Nm pax
.Nd portable archive interchange
.Sh SYNOPSIS
.Nm
.Op Fl rwv
.Op Fl f Ar archive
.Op Fl x Ar format
.Op Ar pattern ...
.Sh DESCRIPTION
The
.Nm
utility shall list, read, or write archive files, or copy directory 
hierarchies.
.Pp
The following options are supported:
.Bl -tag -width indent
.It Fl r
Read an archive file from standard input.
.It Fl w
Write files to standard output in the specified archive format.
.It Fl f Ar archive
Specify the pathname of the input or output archive.
.It Fl x Ar format
Specify the output archive format. The formats supported are
.Sy ustar
(default) and
.Sy cpio .
.El
.Sh OPERANDS
The
.Nm
utility supports four modes of operation:
.Bl -bullet
.It
.Sy List :
Neither
.Fl r
nor
.Fl w
are specified.
.It
.Sy Read :
.Fl r
is specified, but
.Fl w
is not.
.It
.Sy Write :
.Fl w
is specified, but
.Fl r
is not.
.It
.Sy Copy :
Both
.Fl r
and
.Fl w
are specified.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr cpio 1 ,
.Xr tar 1
