.Dd March 27, 2026
.Dt PRINTF 1
.Os Xao
.Sh NAME
.Nm printf
.Nd formatted output
.Sh SYNOPSIS
.Nm
.Ar format
.Op Ar argument ...
.Sh DESCRIPTION
The
.Nm
utility formats and prints its arguments, after the first, under control of the
.Ar format .
The
.Ar format
is a character string which contains three types of objects: plain characters,
which are simply copied to standard output; character escape sequences, which are
converted and then copied to the standard output; and format specifications.
.Pp
The
.Ar format
is reused as often as necessary to satisfy the
.Ar arguments .
Any extra
.Ar arguments
are evaluated as 0 if they are numeric, and as an empty string otherwise.
.Sh EXAMPLES
Print a simple string with a newline:
.Pp
.Dl $ printf "Hello, %s\\n" "World"
.Pp
Use octal escapes:
.Pp
.Dl $ printf "\\101\\n"
.Sh SEE ALSO
.Xr echo 1 ,
.Xr printf 3
