#!/usr/bin/env lua

-- Static ignores that don't follow a pattern
local static_ignores = {
    "inst/",
    "root/",
    "src/web/target/",
    "src/web/public/",
    "*.o",
    "*.a",
    "*.so",
    "*.shlib",
    "*.kmod",
    "*.map",
    ".gdbinit",
    "src/cmd/**/.gdbinit",
    "src/lpts/lpts.json",
    "src/kat/katadm",
    "src/kat/amd64",
    "src/kat/i368",
    "src/kat/xen",
    "src/kat/x86_64",
    "src/kat/machine",
    "src/cmd/**/*.html*"
}

print("# generated by gitignore.lua, do NOT edit!")
for _, entry in ipairs(static_ignores) do
    print(entry)
end

-- Use 'find' to locate all directories under src/cmd
local handle = io.popen("find src/cmd -type d")
if handle then
    for line in handle:lines() do
        -- Extract the directory name (the part after the last /)
        local cmd_name = line:match("([^/]+)$")
        
        -- Ignore the top-level src/cmd directory itself
        if cmd_name and line ~= "src/cmd" then
            -- Construct the path to the potential binary
            local binary_path = line .. "/" .. cmd_name
            
            -- Check if a file with that name actually exists
            local f = io.open(binary_path, "r")
            if f then
                print(binary_path)
                f:close()
            end
        end
    end
    handle:close()
end
