test("cat: read a file", function()
    os.execute("echo 'hello kayoko' > _cat_test")
    local f = io.popen("cat _cat_test")
    local res = f:read("*a"):gsub("%s+", "")
    f:close()
    assert(res == "hellokayoko", "cat failed to read file")
    os.execute("rm _cat_test")
end)

test("cat: stdin via '-'", function()
    -- POSIX: '-' means read from stdin
    local f = io.popen("echo 'test-stdin' | cat -")
    local res = f:read("*a"):match("%S+")
    f:close()
    assert(res == "test-stdin", "cat - failed to read stdin")
end)

test("cat: multiple files concatenated", function()
    os.execute("echo 'a' > _cat_a; echo 'b' > _cat_b")
    local f = io.popen("cat _cat_a _cat_b")
    local res = f:read("*a"):gsub("%s+", "")
    f:close()
    assert(res == "ab", "cat failed to concatenate multiple files")
    os.execute("rm _cat_a _cat_b")
end)
