test("wc: basic line count", function()
    os.execute("printf '1\n2\n3\n' > _wc_test")
    local f = io.popen("wc -l _wc_test")
    local res = f:read("*a"):match("%d+")
    f:close()
    assert(tonumber(res) == 3, "wc -l failed to count lines")
    os.execute("rm _wc_test")
end)

test("wc: word and byte count", function()
    -- "hello world" is 2 words, 11 bytes (no newline here)
    os.execute("printf 'hello world' > _wc_test")
    local f = io.popen("wc -w -c _wc_test")
    local words, bytes = f:read("*a"):match("(%d+)%s+(%d+)")
    f:close()
    assert(tonumber(words) == 2, "wc -w count mismatch")
    assert(tonumber(bytes) == 11, "wc -c count mismatch")
    os.execute("rm _wc_test")
end)

test("wc: stdin handling", function()
    local f = io.popen("echo 'test' | wc -l")
    local res = f:read("*a"):match("%d+")
    f:close()
    assert(tonumber(res) == 1, "wc failed to read from stdin")
end)
